#!/usr/bin/env bash

set -xeuo pipefail

LONICERA_TARGET_IMAGE="${1:-ghcr.io/zirconium-dev/zirconium:latest}"
LONICERA_INCREMENTAL=1
LONICERA_SELINUX=0

DISTRO_UGLYNAME="zirconium"
WORKDIR="/tmp/work"

LIVE_ROOTFS="/var/home/tulip/opt/zirconium-dev/zirconium-liveiso-profiles/mkosi.output/Zirconium_20260505012630_x86-64"
# LIVE_ROOTFS="${WORKDIR}/live-rootfs"
EFI_PARTFS="${WORKDIR}/efi-part"
ISO_ROOTFS="${WORKDIR}/iso-rootfs"

echo "Extracting root filesystem"
mkdir -p "${LIVE_ROOTFS}"
# This will fail most of the time due to ostree references not being there
# /home/linuxbrew/.linuxbrew/bin/crane export "${LONICERA_TARGET_IMAGE}" | tar --xattrs-include='*' --hard-dereference -p -xvf - -C "${LIVE_ROOTFS}" || true

stat "${LIVE_ROOTFS}/usr/bin/bash"
stat "${LIVE_ROOTFS}/usr/lib/systemd/systemd"

mkdir -p "${ISO_ROOTFS}/LiveOS"
sudo mksquashfs "${LIVE_ROOTFS}" "${ISO_ROOTFS}/LiveOS/squashfs.img" -all-root -noappend
# mkfs.erofs -d0 --quiet --all-root -zlz4hc,6 -Eall-fragments,fragdedupe=inode -C1048576 iso-root/LiveOS/squashfs.img embedded-rootfs

install -Dpm0644 "${LIVE_ROOTFS}/usr/lib/systemd/boot/efi/systemd-bootx64.efi" "${EFI_PARTFS}/EFI/BOOT/BOOTX64.EFI"
install -Dpm0644 -t "${EFI_PARTFS}/EFI/systemd/" "${LIVE_ROOTFS}/usr/lib/systemd/boot/efi/systemd-boot"*.efi
install -Dpm0644 -t "${EFI_PARTFS}/EFI/Linux/${DISTRO_UGLYNAME}/" "${LIVE_ROOTFS}/usr/lib/modules/"*/vmlinuz 
install -Dpm0644 -t "${EFI_PARTFS}/EFI/Linux/${DISTRO_UGLYNAME}/" "${LIVE_ROOTFS}/usr/lib/modules/"*/initramfs.img 

mkdir -p "${EFI_PARTFS}/loader/entries"
echo "type1" | tee "${EFI_PARTFS}/loader/entries.srel"
tee "${EFI_PARTFS}/loader/entries/test.conf" <<EOF
title ${DISTRO_UGLYNAME}
version 1
linux /EFI/Linux/${DISTRO_UGLYNAME}/vmlinuz
initrd /EFI/Linux/${DISTRO_UGLYNAME}/initramfs.img
options quiet rhgb root=live:CDLABEL=${DISTRO_UGLYNAME}_boot enforcing=0 rd.live.image systemd.debug-shell=1 rd.systemd.debug-shell=1 systemd.debug-shell=ttyS0 systemd.log_level=debug
EOF

truncate -s 300M "${WORKDIR}/uefi.img"
mkfs.fat -F32 "${WORKDIR}/uefi.img"
mcopy -v -i "${WORKDIR}/uefi.img" -s "${EFI_PARTFS}"/* ::

xorriso -as mkisofs \
    -R \
    -V "${DISTRO_UGLYNAME}_boot" \
    -partition_offset 16 \
    -appended_part_as_gpt \
    -append_partition 2 C12A7328-F81F-11D2-BA4B-00A0C93EC93B "${WORKDIR}/uefi.img" \
    -iso_mbr_part_type EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 \
    -e --interval:appended_partition_2:all:: \
    -no-emul-boot \
    -iso-level 3 \
    -o "${WORKDIR}/${DISTRO_UGLYNAME}.iso" \
    "${ISO_ROOTFS}"
